'use client'
import useSWR from 'swr'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import SectionNews from './SectionNews'
const fetcher = (url: string) => fetch(url).then(r => r.json())
type Mode = 'movie' | 'series' | 'cartoon'
type Item = { id:string; type:string; title:string; originalTitle:string; year:string; image:string; summary:string; genres:string[]; rating:number|null; url:string; trailerUrl:string; source?:string }

const copy: Record<string, any> = {
  en: { title:'Movies / Series / Cartoons', sub:'Catalogue, genres, years, countries and filters', movie:'Movies', series:'Series', cartoon:'Cartoons', sort:'Sort', top:'Top', year:'Year', genre:'Genre', collection:'Collections', country:'Country', quality:'Quality', translation:'Translation', search:'Search...', apply:'Apply', cancel:'Cancel', all:'All', nav:'Navigation panel', genres:'Genres', category:'Category', byYear:'By year', byCountry:'By country', shown:'Shown', rating:'Rating', details:'Details', trailer:'Trailer', more:'More results', noData:'No results', reset:'Reset filters' },
  az: { title:'Kino / Serial / Multfilm', sub:'Kataloq, janr, il, ölkə və filterlər', movie:'Kino', series:'Serial', cartoon:'Multfilm', sort:'Sıralama', top:'TOP', year:'İl', genre:'Janr', collection:'Seçmələr', country:'Ölkə', quality:'Keyfiyyət', translation:'Tərcümə', search:'Axtar...', apply:'Tətbiq et', cancel:'Ləğv et', all:'Hamısı', nav:'Naviqasiya paneli', genres:'Janrlar', category:'Kateqoriya', byYear:'İllərə görə', byCountry:'Ölkələrə görə', shown:'Göstərildi', rating:'Reytinq', details:'Ətraflı', trailer:'Trailer', more:'Daha çox nəticə', noData:'Nəticə yoxdur', reset:'Filterləri sıfırla' },
  ru: { title:'Кино / Сериалы / Мультфильмы', sub:'Каталог, жанры, годы, страны и фильтры', movie:'Фильмы', series:'Сериалы', cartoon:'Мультфильмы', sort:'Сортировка', top:'ТОП', year:'Год', genre:'Жанр', collection:'Подборки', country:'Страна', quality:'Качество', translation:'Перевод', search:'Поиск...', apply:'Применить', cancel:'Отмена', all:'Все', nav:'Панель навигации', genres:'Жанры', category:'Категория', byYear:'По году', byCountry:'По странам', shown:'Показано', rating:'Рейтинг', details:'Подробнее', trailer:'Трейлер', more:'Больше результатов', noData:'Ничего не найдено', reset:'Сбросить фильтры' },
  de: { title:'Filme / Serien / Cartoons', sub:'Katalog, Genres, Jahre, Länder und Filter', movie:'Filme', series:'Serien', cartoon:'Cartoons', sort:'Sortierung', top:'Top', year:'Jahr', genre:'Genre', collection:'Sammlungen', country:'Land', quality:'Qualität', translation:'Übersetzung', search:'Suchen...', apply:'Anwenden', cancel:'Abbrechen', all:'Alle', nav:'Navigation', genres:'Genres', category:'Kategorie', byYear:'Nach Jahr', byCountry:'Nach Ländern', shown:'Gezeigt', rating:'Bewertung', details:'Details', trailer:'Trailer', more:'Mehr Ergebnisse', noData:'Keine Ergebnisse', reset:'Filter zurücksetzen' },
  tr: { title:'Film / Dizi / Çizgi film', sub:'Katalog, türler, yıllar, ülkeler ve filtreler', movie:'Filmler', series:'Diziler', cartoon:'Çizgi film', sort:'Sıralama', top:'TOP', year:'Yıl', genre:'Tür', collection:'Listeler', country:'Ülke', quality:'Kalite', translation:'Çeviri', search:'Ara...', apply:'Uygula', cancel:'İptal', all:'Hepsi', nav:'Navigasyon paneli', genres:'Türler', category:'Kategori', byYear:'Yıla göre', byCountry:'Ülkelere göre', shown:'Gösterildi', rating:'Puan', details:'Detay', trailer:'Fragman', more:'Daha fazla sonuç', noData:'Sonuç yok', reset:'Filtreleri sıfırla' },
}
const genres: Record<Mode,string[]> = { movie:['Drama','Action','Comedy','Adventure','Crime','Thriller','Fantasy','Science-Fiction','Romance','Family'], series:['Drama','Action','Comedy','Adventure','Crime','Thriller','Fantasy','Science-Fiction','Family'], cartoon:['Animation','Family','Comedy','Adventure','Fantasy','Action','Drama','Science-Fiction'] }
const cats: Record<Mode,string[]> = { movie:['All movies','New releases','Popular','Marvel','DC','Book adaptations','Oscar style'], series:['All series','Foreign','Turkish','Russian','Dramas','Anime','TV shows'], cartoon:['All cartoons','Disney','Pixar','Anime','Family','Superheroes'] }
const countries = ['All','American','Turkish','Russian','Indian','Ukrainian','French','German','British','Japanese','Korean']
const qualities = ['All','4K','1080p','HD','WEB-DL','BluRay','CAM']
const translations = ['All','Original','Dubbed','Subtitles','Russian','Turkish','German','Azerbaijani']
const collections = ['All','Top','Popular','New releases','Upcoming','Marvel','DC','Netflix','Disney','Anime']
const years = Array.from({length: new Date().getFullYear() + 3 - 1975 + 1}, (_,i)=>new Date().getFullYear()+3-i)
const sideYears = Array.from({length: 11}, (_,i)=>new Date().getFullYear()+2-i)
function labelMode(m:Mode,t:any){return m==='movie'?t.movie:m==='series'?t.series:t.cartoon}
function apiUrl(mode:Mode, genre:string, year:string, query:string, page:number, lang:string, collection:string){ const p=new URLSearchParams({type:mode,lang,page:String(page)}); if(genre)p.set('genre',genre); if(year)p.set('yearFrom',year),p.set('yearTo',year); if(query.trim())p.set('q',query.trim()); if(collection==='Upcoming')p.set('mode','anticipated'); if(collection==='Top'||collection==='Popular')p.set('mode','trending'); return `/api/entertainment?${p}` }

function Dropdown({label, active, open, setOpen, children}:{label:string; active?:string; open:boolean; setOpen:(v:boolean)=>void; children:React.ReactNode}){return <div className="relative"><button type="button" onClick={()=>setOpen(!open)} className={`min-w-[115px] flex items-center justify-between gap-2 px-3 py-2 text-xs border ${open?'bg-blue-600 border-blue-500 text-white':'bg-[#252525] border-[#3a3a3a] text-gray-300 hover:bg-[#303030]'}`}>{active||label}<ChevronDown className="w-3 h-3"/></button>{open&&<div className="absolute left-0 top-full z-30 mt-1 w-[min(760px,calc(100vw-3rem))] rounded border border-[#333] bg-[#1d1d1d] shadow-2xl">{children}</div>}</div>}
function OptionPanel({items,value,setValue,allLabel}:{items:string[];value:string;setValue:(v:string)=>void;allLabel:string}){return <div className="p-4 grid grid-cols-2 sm:grid-cols-3 gap-3">{items.map(v=>{const val=v==='All'?'':v;return <button type="button" key={v} onClick={()=>setValue(val)} className={`text-left px-3 py-2 rounded ${value===val?'bg-blue-600 text-white':'bg-[#2b2b2b] text-gray-300 hover:bg-[#333]'}`}>{v==='All'?allLabel:v}</button>})}</div>}
function MediaRow({item,t}:{item:Item;t:any}){return <div className="grid grid-cols-[92px,1fr] gap-4 border-b border-[#252525] py-4"><img src={item.image} alt={item.title} className="w-[92px] h-[138px] object-cover bg-gray-800 rounded"/><div className="min-w-0"><div className="flex items-start justify-between gap-2"><h3 className="text-lg font-bold text-gray-200 line-clamp-2">{item.title} <span className="text-gray-500 text-sm">{item.year&&`(${item.year})`}</span></h3><div className="text-right shrink-0"><div className="text-orange-400 text-sm">★ ★ ★ ★ ☆</div><div className="text-xs text-gray-500">{t.rating}: {item.rating||'—'}</div></div></div><p className="mt-2 text-sm text-gray-400 line-clamp-3">{item.summary}</p><p className="mt-2 text-xs text-gray-500">{item.genres?.slice(0,4).join(' / ')} · {item.source||''}</p><div className="mt-3 flex flex-wrap gap-2"><a href={item.url} target="_blank" rel="noreferrer" className="px-3 py-1.5 rounded bg-emerald-700 hover:bg-emerald-600 text-white text-xs">{t.details}</a><a href={item.trailerUrl} target="_blank" rel="noreferrer" className="px-3 py-1.5 rounded bg-gray-700 hover:bg-gray-600 text-white text-xs">{t.trailer}</a></div></div></div>}

export default function EntertainmentWidget(){
 const {lang}=useLang(); const t=copy[lang]||copy.en
 const [collapsed,setCollapsed]=useState(false); const [mode,setMode]=useState<Mode>('movie'); const [genre,setGenre]=useState(''); const [year,setYear]=useState(''); const [query,setQuery]=useState(''); const [page,setPage]=useState(1); const [open,setOpen]=useState<string|null>(null); const [collection,setCollection]=useState(''); const [country,setCountry]=useState(''); const [quality,setQuality]=useState(''); const [translation,setTranslation]=useState(''); const [allItems,setAllItems]=useState<Item[]>([])
 const url=useMemo(()=>apiUrl(mode,genre,year,query,page,lang,collection),[mode,genre,year,query,page,lang,collection]); const {data,error,isLoading}=useSWR<Item[]>(url,fetcher,{refreshInterval:3600000});
 useEffect(()=>{const incoming=(Array.isArray(data)?data:[]).filter(i=>i.type===mode); setAllItems(prev=>page===1?incoming:[...prev,...incoming.filter(i=>!prev.some(p=>p.id===i.id))])},[data,page,mode])
 const items=allItems.filter(i=>(!genre||i.genres?.some(g=>g.toLowerCase()===genre.toLowerCase()))&&(!year||i.year===year))
 const shown=items.length
 const resetPage=()=>{setPage(1);setAllItems([])}
 const setModeReset=(m:Mode)=>{setMode(m);setGenre('');setYear('');setCollection('');setCountry('');setQuality('');setTranslation('');setPage(1);setAllItems([]);setOpen(null)}
 const pick=(fn:(v:string)=>void,v:string)=>{fn(v);resetPage();setOpen(null)}
 const resetAll=()=>{setGenre('');setYear('');setCollection('');setCountry('');setQuality('');setTranslation('');setQuery('');setPage(1);setAllItems([]);setOpen(null)}
 return <div className="overflow-hidden rounded-2xl border border-gray-800 bg-[#121212]"><div onClick={()=>setCollapsed(!collapsed)} className="cursor-pointer border-b border-[#2a2a2a] px-5 py-3 flex items-center justify-between"><div className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl bg-fuchsia-500/15 border border-fuchsia-500/30 flex items-center justify-center"><Film className="w-4 h-4 text-fuchsia-300"/></div><div><h2 className="text-white text-sm font-semibold">{t.title}</h2><p className="text-gray-500 text-xs">{t.sub}</p></div></div><ChevronDown className={`w-4 h-4 text-gray-500 ${collapsed?'':'rotate-180'}`}/></div>{collapsed?<div className="px-5 py-3 text-xs text-gray-500">{labelMode(mode,t)} · {genre||t.all} · {year||t.all}</div>:<div className="grid grid-cols-1 lg:grid-cols-[280px,1fr]">
 <aside className="border-r border-[#2a2a2a] bg-[#1a1a1a] p-4"><h3 className="text-gray-300 font-bold mb-4">{t.nav}</h3><div className="mb-5"><h4 className="text-gray-400 font-bold mb-2">{t.genres}</h4><div className="grid grid-cols-[1fr_auto] gap-x-3 gap-y-1 text-sm">{['All',...genres[mode]].map((g,i)=><button key={g} onClick={()=>{setGenre(g==='All'?'':g);resetPage()}} className={`text-left underline-offset-2 hover:underline ${genre===(g==='All'?'':g)?'text-yellow-400':'text-gray-500'}`}>— {g==='All'?t.all:g}<span className="float-right text-gray-600 ml-3">{Math.max(1200,92000-i*3421)}</span></button>)}</div></div><div className="mb-5"><h4 className="text-gray-400 font-bold mb-2">{t.category}</h4>{cats[mode].map((c,i)=><button key={c} onClick={()=>{setCollection(i===0?'':c.includes('New')?'New releases':c.includes('Popular')?'Popular':c);resetPage()}} className={`w-full flex justify-between text-sm underline mb-1 ${collection&&c.includes(collection)?'text-yellow-400':'text-gray-500'}`}><span>— {c}</span><span>{Math.max(400,19637-i*1800)}</span></button>)}</div><div className="mb-5"><h4 className="text-gray-400 font-bold mb-2">{t.byYear}</h4>{sideYears.map(y=><button key={y} onClick={()=>{setYear(String(y));resetPage()}} className={`block text-sm underline mb-1 ${year===String(y)?'text-yellow-400':'text-gray-500'}`}>{y} года</button>)}</div><div><h4 className="text-gray-400 font-bold mb-2">{t.byCountry}</h4>{countries.slice(1,8).map(c=><button key={c} onClick={()=>setCountry(c)} className={`block text-sm underline mb-1 ${country===c?'text-yellow-400':'text-gray-500'}`}>{c}</button>)}</div></aside>
 <main className="p-4 min-w-0"><div className="grid grid-cols-3 gap-2 mb-4">{([{id:'movie',label:t.movie,icon:Film},{id:'series',label:t.series,icon:Tv},{id:'cartoon',label:t.cartoon,icon:Play}] as any[]).map(x=>{const Icon=x.icon;return <button key={x.id} onClick={()=>setModeReset(x.id)} className={`py-2 rounded border text-sm flex items-center justify-center gap-2 ${mode===x.id?'bg-purple-800/60 border-purple-500 text-white':'bg-[#252525] border-[#3a3a3a] text-gray-300'}`}><Icon className="w-4 h-4"/>{x.label}</button>})}</div><div className="mb-4 flex gap-2"><div className="flex-1 flex items-center gap-2 bg-[#202020] border border-[#333] px-3 py-2"><Search className="w-4 h-4 text-gray-500"/><input value={query} onChange={e=>{setQuery(e.target.value);resetPage()}} placeholder={t.search} className="bg-transparent outline-none text-gray-200 w-full"/></div><Link href={`/entertainment?type=${mode}&genre=${genre}&yearFrom=${year}&yearTo=${year}&q=${encodeURIComponent(query)}`} className="px-4 py-2 bg-blue-700 text-white rounded flex items-center gap-2 text-sm">{t.details}<ExternalLink className="w-4 h-4"/></Link></div>{(country||quality||translation)&&<div className="mb-3 text-xs text-gray-500">Active UI filters: {[country,quality,translation].filter(Boolean).join(' · ')}. These are shown for catalogue style; source APIs may not provide exact quality/translation metadata.</div>}{isLoading&&page===1&&<div className="py-10 text-gray-500 text-center">Loading...</div>}{error&&<div className="py-10 text-red-400 text-center">Error</div>}{!isLoading&&!error&&items.length===0&&<div className="py-10 text-gray-500 text-center">{t.noData}</div>}<div>{items.map(item=><MediaRow key={item.id} item={item} t={t}/>)}</div><div className="pt-4 flex justify-center"><button onClick={()=>setPage(p=>p+1)} className="px-5 py-2 rounded bg-[#2b2b2b] border border-[#444] hover:bg-[#333] text-gray-200">{isLoading?t.search:t.more} · page {page+1}</button></div><SectionNews section="entertainment" tab={mode} accentColor="fuchsia" darkMode /></main></div>}</div>
}
