'use client'
import useSWR from 'swr'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ChevronDown, ExternalLink, Film, Play, Search, Tv, X } from 'lucide-react'
import { useLang } from '@/lib/LanguageContext'

const fetcher = (url: string) => fetch(url).then(r => r.json())
type Mode = 'movie' | 'series' | 'cartoon'
type Item = { id:string; type:string; title:string; originalTitle:string; year:string; image:string; summary:string; genres:string[]; rating:number|null; url:string; trailerUrl:string; source?:string }

const copy: Record<string, any> = {
  en: { title:'Movies / Series / Cartoons', sub:'Catalogue, genres, years, countries and filters', movie:'Movies', series:'Series', cartoon:'Cartoons', sort:'Sort', top:'Top', year:'Year', genre:'Genre', collection:'Collections', country:'Country', quality:'Quality', translation:'Translation', search:'Search...', apply:'Apply', cancel:'Cancel', all:'All', nav:'Navigation panel', genres:'Genres', category:'Category', byYear:'By year', byCountry:'By country', shown:'Shown', rating:'Rating', details:'Details', trailer:'Trailer', more:'More results', noData:'No results' },
  az: { title:'Kino / Serial / Multfilm', sub:'Kataloq, janr, il, ölkə və filterlər', movie:'Kino', series:'Serial', cartoon:'Multfilm', sort:'Sıralama', top:'TOP', year:'İl', genre:'Janr', collection:'Seçmələr', country:'Ölkə', quality:'Keyfiyyət', translation:'Tərcümə', search:'Axtar...', apply:'Tətbiq et', cancel:'Ləğv et', all:'Hamısı', nav:'Naviqasiya paneli', genres:'Janrlar', category:'Kateqoriya', byYear:'İllərə görə', byCountry:'Ölkələrə görə', shown:'Göstərildi', rating:'Reytinq', details:'Ətraflı', trailer:'Trailer', more:'Daha çox nəticə', noData:'Nəticə yoxdur' },
  ru: { title:'Кино / Сериалы / Мультфильмы', sub:'Каталог, жанры, годы, страны и фильтры', movie:'Фильмы', series:'Сериалы', cartoon:'Мультфильмы', sort:'Сортировка', top:'ТОП', year:'Год', genre:'Жанр', collection:'Подборки', country:'Страна', quality:'Качество', translation:'Перевод', search:'Поиск...', apply:'Применить', cancel:'Отмена', all:'Все', nav:'Панель навигации', genres:'Жанры', category:'Категория', byYear:'По году', byCountry:'По странам', shown:'Показано', rating:'Рейтинг', details:'Подробнее', trailer:'Трейлер', more:'Больше результатов', noData:'Ничего не найдено' },
  de: { title:'Filme / Serien / Cartoons', sub:'Katalog, Genres, Jahre, Länder und Filter', movie:'Filme', series:'Serien', cartoon:'Cartoons', sort:'Sortierung', top:'Top', year:'Jahr', genre:'Genre', collection:'Sammlungen', country:'Land', quality:'Qualität', translation:'Übersetzung', search:'Suchen...', apply:'Anwenden', cancel:'Abbrechen', all:'Alle', nav:'Navigation', genres:'Genres', category:'Kategorie', byYear:'Nach Jahr', byCountry:'Nach Ländern', shown:'Gezeigt', rating:'Bewertung', details:'Details', trailer:'Trailer', more:'Mehr Ergebnisse', noData:'Keine Ergebnisse' },
  tr: { title:'Film / Dizi / Çizgi film', sub:'Katalog, türler, yıllar, ülkeler ve filtreler', movie:'Filmler', series:'Diziler', cartoon:'Çizgi film', sort:'Sıralama', top:'TOP', year:'Yıl', genre:'Tür', collection:'Listeler', country:'Ülke', quality:'Kalite', translation:'Çeviri', search:'Ara...', apply:'Uygula', cancel:'İptal', all:'Hepsi', nav:'Navigasyon paneli', genres:'Türler', category:'Kategori', byYear:'Yıla göre', byCountry:'Ülkelere göre', shown:'Gösterildi', rating:'Puan', details:'Detay', trailer:'Fragman', more:'Daha fazla sonuç', noData:'Sonuç yok' },
}
const genres: Record<Mode,string[]> = { movie:['Drama','Action','Comedy','Adventure','Crime','Thriller','Fantasy','Science-Fiction','Romance','Family'], series:['Drama','Action','Comedy','Adventure','Crime','Thriller','Fantasy','Science-Fiction','Family'], cartoon:['Animation','Family','Comedy','Adventure','Fantasy','Action','Drama','Science-Fiction'] }
const cats: Record<Mode,string[]> = { movie:['All movies','New releases','Popular','Marvel','DC','Book adaptations','Oscar style'], series:['All series','Foreign','Turkish','Russian','Dramas','Anime','TV shows'], cartoon:['All cartoons','Disney','Pixar','Anime','Family','Superheroes'] }
const countries = ['All','American','Turkish','Russian','Indian','Ukrainian','French','German','British','Japanese','Korean']
const years = Array.from({length: new Date().getFullYear() + 3 - 1975 + 1}, (_,i)=>new Date().getFullYear()+3-i)
const sideYears = Array.from({length: 11}, (_,i)=>new Date().getFullYear()+2-i)
function labelMode(m:Mode,t:any){return m==='movie'?t.movie:m==='series'?t.series:t.cartoon}
function apiUrl(mode:Mode, genre:string, year:string, query:string, page:number, lang:string){ const p=new URLSearchParams({type:mode,lang,page:String(page)}); if(genre)p.set('genre',genre); if(year)p.set('yearFrom',year),p.set('yearTo',year); if(query.trim())p.set('q',query.trim()); return `/api/entertainment?${p}` }

function Dropdown({label, active, open, setOpen, children}:{label:string; active?:string; open:boolean; setOpen:(v:boolean)=>void; children:React.ReactNode}){return <div className="relative"><button onClick={()=>setOpen(!open)} className={`min-w-[115px] flex items-center justify-between gap-2 px-3 py-2 text-xs border ${open?'bg-blue-600 border-blue-500 text-white':'bg-[#252525] border-[#3a3a3a] text-gray-300 hover:bg-[#303030]'}`}>{active||label}<ChevronDown className="w-3 h-3"/></button>{open&&<div className="absolute left-0 top-full z-30 mt-1 w-[min(760px,calc(100vw-3rem))] rounded border border-[#333] bg-[#1d1d1d] shadow-2xl">{children}</div>}</div>}
function MediaRow({item,t}:{item:Item;t:any}){return <div className="grid grid-cols-[92px,1fr] gap-4 border-b border-[#252525] py-4"><img src={item.image} alt={item.title} className="w-[92px] h-[138px] object-cover bg-gray-800 rounded"/><div className="min-w-0"><div className="flex items-start justify-between gap-2"><h3 className="text-lg font-bold text-gray-200 line-clamp-2">{item.title} <span className="text-gray-500 text-sm">{item.year&&`(${item.year})`}</span></h3><div className="text-right shrink-0"><div className="text-orange-400 text-sm">★ ★ ★ ★ ☆</div><div className="text-xs text-gray-500">{t.rating}: {item.rating||'—'}</div></div></div><p className="mt-2 text-sm text-gray-400 line-clamp-3">{item.summary}</p><p className="mt-2 text-xs text-gray-500">{item.genres?.slice(0,4).join(' / ')} · {item.source||''}</p><div className="mt-3 flex flex-wrap gap-2"><a href={item.url} target="_blank" rel="noreferrer" className="px-3 py-1.5 rounded bg-emerald-700 hover:bg-emerald-600 text-white text-xs">{t.details}</a><a href={item.trailerUrl} target="_blank" rel="noreferrer" className="px-3 py-1.5 rounded bg-gray-700 hover:bg-gray-600 text-white text-xs">{t.trailer}</a></div></div></div>}

export default function EntertainmentWidget(){
 const {lang}=useLang(); const t=copy[lang]||copy.en
 const [collapsed,setCollapsed]=useState(false); const [mode,setMode]=useState<Mode>('movie'); const [genre,setGenre]=useState(''); const [year,setYear]=useState(''); const [query,setQuery]=useState(''); const [page,setPage]=useState(1); const [open,setOpen]=useState<string|null>(null)
 const url=useMemo(()=>apiUrl(mode,genre,year,query,page,lang),[mode,genre,year,query,page,lang]); const {data,error,isLoading}=useSWR<Item[]>(url,fetcher,{refreshInterval:3600000}); const items=(Array.isArray(data)?data:[]).filter(i=>i.type===mode)
 const shown=items.length
 const setModeReset=(m:Mode)=>{setMode(m);setGenre('');setYear('');setPage(1);setOpen(null)}
 return <div className="overflow-hidden rounded-2xl border border-gray-800 bg-[#121212]"><div onClick={()=>setCollapsed(!collapsed)} className="cursor-pointer border-b border-[#2a2a2a] px-5 py-3 flex items-center justify-between"><div className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl bg-fuchsia-500/15 border border-fuchsia-500/30 flex items-center justify-center"><Film className="w-4 h-4 text-fuchsia-300"/></div><div><h2 className="text-white text-sm font-semibold">{t.title}</h2><p className="text-gray-500 text-xs">{t.sub}</p></div></div><ChevronDown className={`w-4 h-4 text-gray-500 ${collapsed?'':'rotate-180'}`}/></div>{collapsed?<div className="px-5 py-3 text-xs text-gray-500">{labelMode(mode,t)} · {genre||t.all} · {year||t.all}</div>:<div className="grid grid-cols-1 lg:grid-cols-[280px,1fr]">
 <aside className="border-r border-[#2a2a2a] bg-[#1a1a1a] p-4"><h3 className="text-gray-300 font-bold mb-4">{t.nav}</h3><div className="mb-5"><h4 className="text-gray-400 font-bold mb-2">{t.genres}</h4><div className="grid grid-cols-[1fr_auto] gap-x-3 gap-y-1 text-sm">{['All',...genres[mode]].map((g,i)=><button key={g} onClick={()=>{setGenre(g==='All'?'':g);setPage(1)}} className={`text-left underline-offset-2 hover:underline ${genre===(g==='All'?'':g)?'text-yellow-400':'text-gray-500'}`}>— {g==='All'?t.all:g}<span className="float-right text-gray-600 ml-3">{Math.max(1200,92000-i*3421)}</span></button>)}</div></div><div className="mb-5"><h4 className="text-gray-400 font-bold mb-2">{t.category}</h4>{cats[mode].map((c,i)=><div key={c} className="flex justify-between text-sm text-gray-500 underline mb-1"><span>— {c}</span><span>{Math.max(400,19637-i*1800)}</span></div>)}</div><div className="mb-5"><h4 className="text-gray-400 font-bold mb-2">{t.byYear}</h4>{sideYears.map(y=><button key={y} onClick={()=>{setYear(String(y));setPage(1)}} className={`block text-sm underline mb-1 ${year===String(y)?'text-yellow-400':'text-gray-500'}`}>{y} года</button>)}</div><div><h4 className="text-gray-400 font-bold mb-2">{t.byCountry}</h4>{countries.slice(1,8).map(c=><div key={c} className="text-sm text-gray-500 underline mb-1">{c}</div>)}</div></aside>
 <main className="p-4 min-w-0"><div className="flex flex-col xl:flex-row xl:items-center justify-between gap-3 mb-4"><div className="flex flex-wrap items-center gap-1"><span className="text-gray-500 text-sm mr-2">{t.sort}:</span><button className="px-4 py-2 bg-[#252525] border border-[#3a3a3a] text-gray-300 text-xs">{t.top} за 3 дня</button><Dropdown label={t.year} active={year} open={open==='year'} setOpen={v=>setOpen(v?'year':null)}><div className="p-4"><div className="flex justify-between border-b border-[#333] pb-3 mb-3"><span className="text-yellow-400 font-bold uppercase">{t.year}</span><div className="flex items-center gap-2"><input placeholder={t.search} className="bg-transparent text-sm text-gray-300 outline-none"/><X className="w-4 h-4 text-gray-500"/></div></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 max-h-80 overflow-auto pr-2">{years.map(y=><label key={y} className="flex items-center gap-2 text-gray-200"><input type="checkbox" checked={year===String(y)} onChange={()=>setYear(year===String(y)?'':String(y))}/>{y}</label>)}</div><div className="mt-4 flex gap-2"><button onClick={()=>{setPage(1);setOpen(null)}} className="px-4 py-2 bg-emerald-700 text-white text-sm">{t.apply}</button><button onClick={()=>{setYear('');setOpen(null)}} className="px-4 py-2 bg-gray-600 text-white text-sm">{t.cancel}</button></div></div></Dropdown><Dropdown label={t.genre} active={genre} open={open==='genre'} setOpen={v=>setOpen(v?'genre':null)}><div className="p-4 grid grid-cols-2 sm:grid-cols-3 gap-3">{['',...genres[mode]].map(g=><button key={g||'all'} onClick={()=>{setGenre(g);setPage(1);setOpen(null)}} className={`text-left px-3 py-2 rounded ${genre===g?'bg-blue-600 text-white':'bg-[#2b2b2b] text-gray-300'}`}>{g||t.all}</button>)}</div></Dropdown>{[t.collection,t.country,t.quality,t.translation].map(x=><button key={x} className="min-w-[110px] flex items-center justify-between gap-2 px-3 py-2 text-xs bg-[#252525] border border-[#3a3a3a] text-gray-400">{x}<ChevronDown className="w-3 h-3"/></button>)}</div><div className="text-gray-500 text-sm">{t.shown}: <b className="text-gray-300">{shown}</b></div></div>
 <div className="grid grid-cols-3 gap-2 mb-4">{([{id:'movie',label:t.movie,icon:Film},{id:'series',label:t.series,icon:Tv},{id:'cartoon',label:t.cartoon,icon:Play}] as any[]).map(x=>{const Icon=x.icon;return <button key={x.id} onClick={()=>setModeReset(x.id)} className={`py-2 rounded border text-sm flex items-center justify-center gap-2 ${mode===x.id?'bg-purple-800/60 border-purple-500 text-white':'bg-[#252525] border-[#3a3a3a] text-gray-300'}`}><Icon className="w-4 h-4"/>{x.label}</button>})}</div><div className="mb-4 flex gap-2"><div className="flex-1 flex items-center gap-2 bg-[#202020] border border-[#333] px-3 py-2"><Search className="w-4 h-4 text-gray-500"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={t.search} className="bg-transparent outline-none text-gray-200 w-full"/></div><Link href={`/entertainment?type=${mode}&genre=${genre}&yearFrom=${year}&yearTo=${year}&q=${encodeURIComponent(query)}`} className="px-4 py-2 bg-blue-700 text-white rounded flex items-center gap-2 text-sm">{t.details}<ExternalLink className="w-4 h-4"/></Link></div>{isLoading&&<div className="py-10 text-gray-500 text-center">Loading...</div>}{error&&<div className="py-10 text-red-400 text-center">Error</div>}{!isLoading&&!error&&items.length===0&&<div className="py-10 text-gray-500 text-center">{t.noData}</div>}<div>{items.map(item=><MediaRow key={item.id} item={item} t={t}/>)}</div><div className="pt-4 flex justify-center"><button onClick={()=>setPage(p=>p+1)} className="px-5 py-2 rounded bg-[#2b2b2b] border border-[#444] hover:bg-[#333] text-gray-200">{t.more} · page {page+1}</button></div></main>
 </div>}</div>
}
