export interface Airport {
  iata: string
  name: string
  city: string
  country: string
}

export const AIRPORTS: Airport[] = [
  { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany' },
  { iata: 'MUC', name: 'Munich Airport', city: 'Munich', country: 'Germany' },
  { iata: 'BER', name: 'Berlin Brandenburg', city: 'Berlin', country: 'Germany' },
  { iata: 'DUS', name: 'D\u00fcsseldorf Airport', city: 'D\u00fcsseldorf', country: 'Germany' },
  { iata: 'HAM', name: 'Hamburg Airport', city: 'Hamburg', country: 'Germany' },
  { iata: 'STR', name: 'Stuttgart Airport', city: 'Stuttgart', country: 'Germany' },
  { iata: 'CGN', name: 'Cologne Bonn Airport', city: 'Cologne', country: 'Germany' },
  { iata: 'HAJ', name: 'Hannover Airport', city: 'Hannover', country: 'Germany' },
  { iata: 'NUE', name: 'Nuremberg Airport', city: 'Nuremberg', country: 'Germany' },
  { iata: 'LEJ', name: 'Leipzig/Halle Airport', city: 'Leipzig', country: 'Germany' },
  { iata: 'DTM', name: 'Dortmund Airport', city: 'Dortmund', country: 'Germany' },
  { iata: 'PMI', name: 'Palma de Mallorca', city: 'Mallorca', country: 'Spain' },
  { iata: 'BCN', name: 'Barcelona El Prat', city: 'Barcelona', country: 'Spain' },
  { iata: 'MAD', name: 'Madrid Barajas', city: 'Madrid', country: 'Spain' },
  { iata: 'AGP', name: 'M\u00e1laga Airport', city: 'M\u00e1laga', country: 'Spain' },
  { iata: 'ALC', name: 'Alicante Airport', city: 'Alicante', country: 'Spain' },
  { iata: 'TFS', name: 'Tenerife South', city: 'Tenerife', country: 'Spain' },
  { iata: 'LPA', name: 'Gran Canaria Airport', city: 'Gran Canaria', country: 'Spain' },
  { iata: 'FUE', name: 'Fuerteventura Airport', city: 'Fuerteventura', country: 'Spain' },
  { iata: 'IBZ', name: 'Ibiza Airport', city: 'Ibiza', country: 'Spain' },
  { iata: 'LHR', name: 'London Heathrow', city: 'London', country: 'United Kingdom' },
  { iata: 'LGW', name: 'London Gatwick', city: 'London', country: 'United Kingdom' },
  { iata: 'STN', name: 'London Stansted', city: 'London', country: 'United Kingdom' },
  { iata: 'MAN', name: 'Manchester Airport', city: 'Manchester', country: 'United Kingdom' },
  { iata: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh', country: 'United Kingdom' },
  { iata: 'CDG', name: 'Paris Charles de Gaulle', city: 'Paris', country: 'France' },
  { iata: 'ORY', name: 'Paris Orly', city: 'Paris', country: 'France' },
  { iata: 'NCE', name: 'Nice C\u00f4te d\u2019Azur', city: 'Nice', country: 'France' },
  { iata: 'MRS', name: 'Marseille Provence', city: 'Marseille', country: 'France' },
  { iata: 'LYS', name: 'Lyon Saint-Exup\u00e9ry', city: 'Lyon', country: 'France' },
  { iata: 'FCO', name: 'Rome Fiumicino', city: 'Rome', country: 'Italy' },
  { iata: 'MXP', name: 'Milan Malpensa', city: 'Milan', country: 'Italy' },
  { iata: 'VCE', name: 'Venice Marco Polo', city: 'Venice', country: 'Italy' },
  { iata: 'NAP', name: 'Naples Airport', city: 'Naples', country: 'Italy' },
  { iata: 'CTA', name: 'Catania Airport', city: 'Catania', country: 'Italy' },
  { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam', country: 'Netherlands' },
  { iata: 'VIE', name: 'Vienna Airport', city: 'Vienna', country: 'Austria' },
  { iata: 'SZG', name: 'Salzburg Airport', city: 'Salzburg', country: 'Austria' },
  { iata: 'INN', name: 'Innsbruck Airport', city: 'Innsbruck', country: 'Austria' },
  { iata: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland' },
  { iata: 'GVA', name: 'Geneva Airport', city: 'Geneva', country: 'Switzerland' },
  { iata: 'BSL', name: 'Basel EuroAirport', city: 'Basel', country: 'Switzerland' },
  { iata: 'LIS', name: 'Lisbon Airport', city: 'Lisbon', country: 'Portugal' },
  { iata: 'FAO', name: 'Faro Airport', city: 'Faro', country: 'Portugal' },
  { iata: 'OPO', name: 'Porto Airport', city: 'Porto', country: 'Portugal' },
  { iata: 'ATH', name: 'Athens Airport', city: 'Athens', country: 'Greece' },
  { iata: 'HER', name: 'Heraklion Airport', city: 'Crete', country: 'Greece' },
  { iata: 'RHO', name: 'Rhodes Airport', city: 'Rhodes', country: 'Greece' },
  { iata: 'CFU', name: 'Corfu Airport', city: 'Corfu', country: 'Greece' },
  { iata: 'SKG', name: 'Thessaloniki Airport', city: 'Thessaloniki', country: 'Greece' },
  { iata: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey' },
  { iata: 'SAW', name: 'Istanbul Sabiha G\u00f6k\u00e7en', city: 'Istanbul', country: 'Turkey' },
  { iata: 'AYT', name: 'Antalya Airport', city: 'Antalya', country: 'Turkey' },
  { iata: 'ADB', name: 'Izmir Adnan Menderes', city: 'Izmir', country: 'Turkey' },
  { iata: 'DLM', name: 'Dalaman Airport', city: 'Dalaman', country: 'Turkey' },
  { iata: 'BJV', name: 'Bodrum Milas Airport', city: 'Bodrum', country: 'Turkey' },
  { iata: 'ESB', name: 'Ankara Esenbo\u011fa', city: 'Ankara', country: 'Turkey' },
  { iata: 'GYD', name: 'Heydar Aliyev Airport', city: 'Baku', country: 'Azerbaijan' },
  { iata: 'GBB', name: 'Gabala Airport', city: 'Gabala', country: 'Azerbaijan' },
  { iata: 'NAJ', name: 'Nakhchivan Airport', city: 'Nakhchivan', country: 'Azerbaijan' },
  { iata: 'TBS', name: 'Tbilisi Airport', city: 'Tbilisi', country: 'Georgia' },
  { iata: 'BUS', name: 'Batumi Airport', city: 'Batumi', country: 'Georgia' },
  { iata: 'KUT', name: 'Kutaisi Airport', city: 'Kutaisi', country: 'Georgia' },
  { iata: 'SVO', name: 'Moscow Sheremetyevo', city: 'Moscow', country: 'Russia' },
  { iata: 'DME', name: 'Moscow Domodedovo', city: 'Moscow', country: 'Russia' },
  { iata: 'LED', name: 'St. Petersburg Pulkovo', city: 'St. Petersburg', country: 'Russia' },
  { iata: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'UAE' },
  { iata: 'AUH', name: 'Abu Dhabi Airport', city: 'Abu Dhabi', country: 'UAE' },
  { iata: 'DOH', name: 'Hamad International', city: 'Doha', country: 'Qatar' },
  { iata: 'JFK', name: 'New York JFK', city: 'New York', country: 'USA' },
  { iata: 'EWR', name: 'Newark Liberty', city: 'New York', country: 'USA' },
  { iata: 'LAX', name: 'Los Angeles Airport', city: 'Los Angeles', country: 'USA' },
  { iata: 'ORD', name: "Chicago O\u2019Hare", city: 'Chicago', country: 'USA' },
  { iata: 'MIA', name: 'Miami Airport', city: 'Miami', country: 'USA' },
  { iata: 'SFO', name: 'San Francisco Airport', city: 'San Francisco', country: 'USA' },
  { iata: 'ATL', name: 'Atlanta Hartsfield', city: 'Atlanta', country: 'USA' },
  { iata: 'BKK', name: 'Bangkok Suvarnabhumi', city: 'Bangkok', country: 'Thailand' },
  { iata: 'HKT', name: 'Phuket Airport', city: 'Phuket', country: 'Thailand' },
  { iata: 'SIN', name: 'Singapore Changi', city: 'Singapore', country: 'Singapore' },
  { iata: 'KUL', name: 'Kuala Lumpur KLIA', city: 'Kuala Lumpur', country: 'Malaysia' },
  { iata: 'NRT', name: 'Tokyo Narita', city: 'Tokyo', country: 'Japan' },
  { iata: 'HND', name: 'Tokyo Haneda', city: 'Tokyo', country: 'Japan' },
  { iata: 'ICN', name: 'Seoul Incheon', city: 'Seoul', country: 'South Korea' },
  { iata: 'PEK', name: 'Beijing Capital', city: 'Beijing', country: 'China' },
  { iata: 'PVG', name: 'Shanghai Pudong', city: 'Shanghai', country: 'China' },
  { iata: 'HKG', name: 'Hong Kong International', city: 'Hong Kong', country: 'China' },
  { iata: 'DEL', name: 'Delhi Indira Gandhi', city: 'Delhi', country: 'India' },
  { iata: 'BOM', name: 'Mumbai Airport', city: 'Mumbai', country: 'India' },
  { iata: 'CAI', name: 'Cairo Airport', city: 'Cairo', country: 'Egypt' },
  { iata: 'HRG', name: 'Hurghada Airport', city: 'Hurghada', country: 'Egypt' },
  { iata: 'SSH', name: 'Sharm El Sheikh', city: 'Sharm El Sheikh', country: 'Egypt' },
  { iata: 'CMN', name: 'Casablanca Mohammed V', city: 'Casablanca', country: 'Morocco' },
  { iata: 'RAK', name: 'Marrakech Airport', city: 'Marrakech', country: 'Morocco' },
  { iata: 'TUN', name: 'Tunis Airport', city: 'Tunis', country: 'Tunisia' },
  { iata: 'MLE', name: 'Mal\u00e9 Airport', city: 'Mal\u00e9', country: 'Maldives' },
  { iata: 'MRU', name: 'Mauritius Airport', city: 'Mauritius', country: 'Mauritius' },
  { iata: 'CUN', name: 'Canc\u00fan Airport', city: 'Canc\u00fan', country: 'Mexico' },
  { iata: 'HAV', name: 'Havana Airport', city: 'Havana', country: 'Cuba' },
  { iata: 'GRU', name: 'S\u00e3o Paulo Guarulhos', city: 'S\u00e3o Paulo', country: 'Brazil' },
  { iata: 'SYD', name: 'Sydney Airport', city: 'Sydney', country: 'Australia' },
  { iata: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', country: 'Australia' },
  { iata: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
  { iata: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norway' },
  { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden' },
  { iata: 'HEL', name: 'Helsinki Airport', city: 'Helsinki', country: 'Finland' },
  { iata: 'WAW', name: 'Warsaw Chopin', city: 'Warsaw', country: 'Poland' },
  { iata: 'KRK', name: 'Krak\u00f3w Airport', city: 'Krak\u00f3w', country: 'Poland' },
  { iata: 'PRG', name: 'Prague Airport', city: 'Prague', country: 'Czech Republic' },
  { iata: 'BUD', name: 'Budapest Airport', city: 'Budapest', country: 'Hungary' },
  { iata: 'OTP', name: 'Bucharest Otopeni', city: 'Bucharest', country: 'Romania' },
  { iata: 'SOF', name: 'Sofia Airport', city: 'Sofia', country: 'Bulgaria' },
  { iata: 'VAR', name: 'Varna Airport', city: 'Varna', country: 'Bulgaria' },
  { iata: 'BOJ', name: 'Burgas Airport', city: 'Burgas', country: 'Bulgaria' },
  { iata: 'ZAG', name: 'Zagreb Airport', city: 'Zagreb', country: 'Croatia' },
  { iata: 'DBV', name: 'Dubrovnik Airport', city: 'Dubrovnik', country: 'Croatia' },
  { iata: 'SPU', name: 'Split Airport', city: 'Split', country: 'Croatia' },
  { iata: 'BRU', name: 'Brussels Airport', city: 'Brussels', country: 'Belgium' },
  { iata: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'Ireland' },
  { iata: 'TLV', name: 'Tel Aviv Ben Gurion', city: 'Tel Aviv', country: 'Israel' },
  { iata: 'JNB', name: 'Johannesburg OR Tambo', city: 'Johannesburg', country: 'South Africa' },
  { iata: 'CPT', name: 'Cape Town Airport', city: 'Cape Town', country: 'South Africa' },
  { iata: 'ADD', name: 'Addis Ababa Bole', city: 'Addis Ababa', country: 'Ethiopia' },
  { iata: 'NBO', name: 'Nairobi Jomo Kenyatta', city: 'Nairobi', country: 'Kenya' },
  { iata: 'MBA', name: 'Mombasa Airport', city: 'Mombasa', country: 'Kenya' },
  { iata: 'ZNZ', name: 'Zanzibar Airport', city: 'Zanzibar', country: 'Tanzania' },
]

export const CITIES: string[] = [
  'Mallorca', 'Barcelona', 'Madrid', 'M\u00e1laga', 'Alicante', 'Tenerife', 'Gran Canaria', 'Ibiza', 'Fuerteventura',
  'London', 'Manchester', 'Edinburgh',
  'Paris', 'Nice', 'Marseille', 'Lyon',
  'Rome', 'Milan', 'Venice', 'Naples', 'Florence', 'Catania',
  'Amsterdam', 'Rotterdam',
  'Vienna', 'Salzburg', 'Innsbruck',
  'Zurich', 'Geneva', 'Basel',
  'Lisbon', 'Porto', 'Faro', 'Algarve',
  'Athens', 'Crete', 'Rhodes', 'Corfu', 'Santorini', 'Mykonos', 'Thessaloniki',
  'Istanbul', 'Antalya', 'Bodrum', 'Izmir', 'Dalaman', 'Ankara',
  'Baku', 'Gabala', 'Nakhchivan',
  'Tbilisi', 'Batumi', 'Kutaisi',
  'Moscow', 'St. Petersburg',
  'Dubai', 'Abu Dhabi',
  'Doha',
  'New York', 'Los Angeles', 'Miami', 'San Francisco', 'Chicago', 'Atlanta',
  'Bangkok', 'Phuket', 'Pattaya',
  'Singapore',
  'Kuala Lumpur',
  'Tokyo', 'Osaka', 'Kyoto',
  'Seoul',
  'Beijing', 'Shanghai', 'Hong Kong',
  'Delhi', 'Mumbai', 'Goa',
  'Cairo', 'Hurghada', 'Sharm El Sheikh',
  'Casablanca', 'Marrakech',
  'Tunis',
  'Maldives', 'Mal\u00e9',
  'Mauritius',
  'Canc\u00fan',
  'Havana',
  'S\u00e3o Paulo', 'Rio de Janeiro',
  'Sydney', 'Melbourne',
  'Copenhagen',
  'Oslo',
  'Stockholm',
  'Helsinki',
  'Warsaw', 'Krak\u00f3w',
  'Prague',
  'Budapest',
  'Bucharest',
  'Sofia', 'Varna', 'Burgas',
  'Zagreb', 'Dubrovnik', 'Split',
  'Brussels',
  'Dublin',
  'Tel Aviv',
  'Johannesburg', 'Cape Town',
  'Nairobi', 'Mombasa',
  'Zanzibar',
  'Frankfurt', 'Munich', 'Berlin', 'D\u00fcsseldorf', 'Hamburg', 'Stuttgart', 'Cologne', 'Hannover',
]
