export type FactCategory = {
  id: string
  emoji: string
  title: string
  description: string
}

export type MindBlowingFact = {
  title: string
  text: string
  category: string
}

type FactSeed = {
  title: string
  detail: string
}

export const factCategories: FactCategory[] = [
  { id: 'astronomy', emoji: '🔭', title: 'Astronomy', description: 'Strange truths about stars, planets, galaxies, and the universe.' },
  { id: 'history', emoji: '🏺', title: 'History', description: 'Shocking, forgotten, and unbelievable moments from the past.' },
  { id: 'human', emoji: '🧠', title: 'Human', description: 'Mind-blowing facts about the body, brain, senses, and behavior.' },
  { id: 'nature', emoji: '🌿', title: 'Nature', description: 'Wild facts about plants, ecosystems, storms, and Earth systems.' },
  { id: 'animals', emoji: '🐾', title: 'Animals', description: 'Amazing facts about creatures that feel almost unreal.' },
  { id: 'science', emoji: '⚛️', title: 'Science', description: 'Facts from physics, biology, chemistry, and modern discoveries.' },
  { id: 'ocean', emoji: '🌊', title: 'Ocean', description: 'Deep-sea mysteries, strange marine life, and hidden water worlds.' },
  { id: 'space', emoji: '🚀', title: 'Space', description: 'Cosmic facts about black holes, missions, planets, and time.' },
  { id: 'earth', emoji: '🌍', title: 'Earth', description: 'Unbelievable facts about our planet, rocks, climate, and geography.' },
  { id: 'technology', emoji: '🤖', title: 'Technology', description: 'Surprising facts about inventions, AI, machines, and the digital world.' },
  { id: 'psychology', emoji: '🌀', title: 'Psychology', description: 'Strange facts about memory, perception, decisions, and emotions.' },
  { id: 'mysteries', emoji: '🕵️', title: 'Mysteries', description: 'Unexplained stories, puzzling places, and strange unsolved questions.' },
  { id: 'ancient-world', emoji: '🏛️', title: 'Ancient World', description: 'Mind-blowing facts about ancient civilizations and lost knowledge.' },
  { id: 'weird-facts', emoji: '✨', title: 'Weird Facts', description: 'The kind of facts that sound fake, but make you want to learn more.' },
]

const topicAngles = [
  { prefix: 'Did you know?', focus: 'The surprising part is the scale, mechanism, or hidden detail behind it.' },
  { prefix: 'Mind-blowing angle', focus: 'This topic works well as a curiosity hook because it sounds impossible at first.' },
  { prefix: 'Shorts idea', focus: 'Use it as a quick visual story with a strong opening and a surprising reveal.' },
  { prefix: 'Deep fact', focus: 'The more you look into it, the stranger and more connected it becomes.' },
  { prefix: 'Visual hook', focus: 'It can be shown with dramatic images, simple comparisons, and one clear explanation.' },
]

const topicSeeds: Record<string, FactSeed[]> = {
  astronomy: [
    { title: 'A day on Venus is longer than its year', detail: 'Venus rotates so slowly that one spin takes longer than one orbit around the Sun.' },
    { title: 'Neutron stars are city-sized monsters', detail: 'A tiny-looking neutron star can hold more mass than the Sun.' },
    { title: 'Some stars are older than our solar system', detail: 'The night sky contains ancient stars that formed billions of years before Earth.' },
    { title: 'Galaxies can collide without most stars touching', detail: 'The spaces between stars are so enormous that galaxy collisions are mostly gravitational chaos.' },
    { title: 'Pulsars behave like cosmic lighthouses', detail: 'They spin rapidly and send beams of radiation through space.' },
    { title: 'The universe has giant empty regions', detail: 'Cosmic voids are enormous areas with very few galaxies.' },
    { title: 'Some planets orbit two stars', detail: 'Circumbinary planets experience double sunsets like science fiction.' },
    { title: 'A supernova can outshine a galaxy', detail: 'One exploding star can briefly become brighter than billions of stars together.' },
    { title: 'Black holes can bend light', detail: 'Their gravity can distort the path of light and magnify objects behind them.' },
    { title: 'The Moon is slowly moving away', detail: 'The Moon drifts a little farther from Earth over time.' },
    { title: 'Comets are frozen time capsules', detail: 'They preserve ancient material from the early solar system.' },
    { title: 'The Sun has weather', detail: 'Solar storms can affect satellites, radio signals, and power systems.' },
    { title: 'Brown dwarfs are failed stars', detail: 'They are too massive to be planets but not massive enough to shine like stars.' },
    { title: 'Some galaxies have supermassive black holes', detail: 'Many galaxy centers contain black holes millions or billions of times the Sun’s mass.' },
    { title: 'Meteor showers come from comet debris', detail: 'Earth passes through trails of dust left behind by comets.' },
    { title: 'Stars are born in dusty clouds', detail: 'Stellar nurseries collapse under gravity and create new stars.' },
    { title: 'Quasars are powered by black holes', detail: 'They are among the brightest objects in the universe.' },
    { title: 'The sky shows the past', detail: 'Light takes time to travel, so distant objects are seen as they were long ago.' },
    { title: 'There may be rogue planets', detail: 'Some planets may drift through space without orbiting any star.' },
    { title: 'The universe is still expanding', detail: 'Space itself continues to stretch on cosmic scales.' },
  ],
  history: [
    { title: 'Cleopatra lived closer to smartphones than pyramids', detail: 'The Great Pyramid was already ancient during Cleopatra’s lifetime.' },
    { title: 'Oxford University is older than the Aztec Empire', detail: 'Teaching at Oxford began before the Aztec Empire rose.' },
    { title: 'Roman concrete could self-heal', detail: 'Some ancient concrete lasted for millennia because of its chemistry.' },
    { title: 'The Silk Road was a network, not one road', detail: 'It linked many cities, cultures, and trade routes across continents.' },
    { title: 'Ancient libraries shaped civilization', detail: 'Knowledge centers collected texts, maps, science, and politics.' },
    { title: 'Vikings navigated huge distances', detail: 'They crossed seas using stars, landmarks, and practical experience.' },
    { title: 'The printing press changed power', detail: 'Mass printing accelerated science, politics, religion, and education.' },
    { title: 'Ancient calendars were advanced', detail: 'Many civilizations tracked seasons, astronomy, and rituals with high precision.' },
    { title: 'Some old cities are still inhabited', detail: 'Human settlement can continue in the same place for thousands of years.' },
    { title: 'The Mongol Empire used a postal relay', detail: 'Fast communication helped manage a massive territory.' },
    { title: 'Coins are tiny history books', detail: 'They reveal rulers, trade, symbols, languages, and economic systems.' },
    { title: 'Ancient shipwrecks preserve trade stories', detail: 'Cargo remains can show what people bought, sold, and valued.' },
    { title: 'Maps used to mix science and myth', detail: 'Early maps often combined real geography with imagination.' },
    { title: 'The Bronze Age collapse reshaped the world', detail: 'Several advanced societies declined around the same era.' },
    { title: 'Medieval medicine mixed observation and belief', detail: 'Some practices were useful, while others were based on wrong theories.' },
    { title: 'Ancient messages were encrypted', detail: 'Rulers and armies used codes long before computers.' },
    { title: 'Ice Age humans made art', detail: 'Cave paintings show complex symbolism and culture.' },
    { title: 'Forgotten empires changed borders', detail: 'Some powerful states disappeared from popular memory.' },
    { title: 'Industrial inventions changed daily life', detail: 'Factories, engines, and electricity reshaped how people lived and worked.' },
    { title: 'Archaeology keeps rewriting history', detail: 'New discoveries can change what we think we know about the past.' },
  ],
  human: [
    { title: 'Your brain edits reality', detail: 'It fills gaps, filters details, and builds a smooth version of the world.' },
    { title: 'Humans faintly glow', detail: 'The body emits tiny amounts of visible light that our eyes cannot see.' },
    { title: 'Your stomach lining renews quickly', detail: 'It protects you from powerful digestive acid.' },
    { title: 'Your memory is reconstructed', detail: 'Remembering is more like rebuilding than replaying a video.' },
    { title: 'Your microbiome affects you', detail: 'Microbes in and on your body interact with digestion and immunity.' },
    { title: 'Blood vessels are incredibly long', detail: 'The circulatory system reaches almost every living tissue.' },
    { title: 'Your eyes have blind spots', detail: 'The brain fills them so smoothly you usually never notice.' },
    { title: 'Sleep helps memory', detail: 'The brain processes and reorganizes information during sleep.' },
    { title: 'Taste is connected to smell', detail: 'Much of flavor depends on aroma, not just the tongue.' },
    { title: 'Bones are living tissue', detail: 'They remodel, repair, and adapt to stress over time.' },
    { title: 'Your immune system remembers', detail: 'Immune memory helps respond faster to familiar threats.' },
    { title: 'Reflexes bypass slow thinking', detail: 'Some reactions happen before conscious processing catches up.' },
    { title: 'Your skin constantly renews', detail: 'Old cells are shed and replaced throughout life.' },
    { title: 'Dreams can mix memory and emotion', detail: 'The sleeping brain creates strange combinations of experience.' },
    { title: 'Language changes the brain', detail: 'Learning languages builds flexible networks for sound, meaning, and memory.' },
    { title: 'Your heartbeat is not perfectly steady', detail: 'Healthy hearts constantly adjust to the body’s needs.' },
    { title: 'Stress changes perception', detail: 'The body prioritizes threat response and narrows attention.' },
    { title: 'Humans are pattern machines', detail: 'The brain searches for meaning even in random information.' },
    { title: 'Your body regulates heat constantly', detail: 'Sweating, blood flow, and metabolism help maintain temperature.' },
    { title: 'Pain is produced by the brain', detail: 'Signals from the body are interpreted and shaped by context.' },
  ],
  nature: [
    { title: 'Some fungi can control insects', detail: 'Certain fungi influence insect behavior to spread spores.' },
    { title: 'Trees can send warning signals', detail: 'Plants use chemicals and underground networks to respond to stress.' },
    { title: 'Lightning can make glass', detail: 'Sand can fuse into glassy tubes after a lightning strike.' },
    { title: 'Carnivorous plants digest animals', detail: 'They evolved traps to survive in nutrient-poor environments.' },
    { title: 'Seeds can wait for years', detail: 'Some seeds remain dormant until conditions are right.' },
    { title: 'Deserts can bloom suddenly', detail: 'Rain can trigger rapid waves of flowers and life.' },
    { title: 'Coral reefs are living cities', detail: 'They host dense communities of animals, algae, and microbes.' },
    { title: 'Forests can move over time', detail: 'Climate and seed dispersal shift tree populations slowly.' },
    { title: 'Some plants communicate through scent', detail: 'Chemical signals can warn neighbors or attract defenders.' },
    { title: 'Fire can help ecosystems', detail: 'Some plants need fire to release seeds or clear competition.' },
    { title: 'Mangroves protect coastlines', detail: 'Their roots slow waves and create nurseries for marine life.' },
    { title: 'Giant kelp grows fast', detail: 'Kelp forests can expand rapidly under good conditions.' },
    { title: 'Peatlands store huge carbon', detail: 'Wet soils slow decay and trap organic matter.' },
    { title: 'Permafrost preserves ancient material', detail: 'Frozen ground can hold plants, animals, and microbes for long periods.' },
    { title: 'Pollination can be a trick', detail: 'Some flowers imitate scents or shapes to attract pollinators.' },
    { title: 'Rainforests create their own humidity', detail: 'Plants release water vapor that feeds local weather.' },
    { title: 'Living fossils still exist', detail: 'Some species resemble ancient relatives from deep time.' },
    { title: 'Volcanic islands start empty', detail: 'Life colonizes new rock step by step.' },
    { title: 'Bioluminescent fungi glow', detail: 'Some fungi produce light through chemical reactions.' },
    { title: 'Seasonal cycles guide life', detail: 'Plants and animals respond to light, temperature, and timing.' },
  ],
  animals: [
    { title: 'Pistol shrimp create shockwaves', detail: 'Their claw snap produces a collapsing bubble that stuns prey.' },
    { title: 'Octopuses have three hearts', detail: 'Two pump blood through gills and one pumps through the body.' },
    { title: 'Tardigrades survive extremes', detail: 'They can endure drying, freezing, radiation, and vacuum for a time.' },
    { title: 'Crows solve complex problems', detail: 'They use tools, remember faces, and plan actions.' },
    { title: 'Elephants communicate through vibrations', detail: 'Low sounds can travel through ground and air.' },
    { title: 'Bees dance directions', detail: 'Honeybees share food locations through movement patterns.' },
    { title: 'Whales sing long songs', detail: 'Some whale songs can travel huge distances underwater.' },
    { title: 'Ant colonies act like superorganisms', detail: 'Individual ants create complex collective behavior.' },
    { title: 'Axolotls regrow body parts', detail: 'They can regenerate limbs and other tissues.' },
    { title: 'Geckos stick with tiny forces', detail: 'Microscopic hairs help them climb smooth surfaces.' },
    { title: 'Mantis shrimp see unusual colors', detail: 'Their eyes detect polarized light and many wavelengths.' },
    { title: 'Dolphins use signature whistles', detail: 'Individuals can have unique sound patterns.' },
    { title: 'Bats navigate with echoes', detail: 'Echolocation turns sound reflections into a map.' },
    { title: 'Some frogs survive freezing', detail: 'They tolerate ice formation during winter dormancy.' },
    { title: 'Spider silk is incredibly strong', detail: 'It combines flexibility and strength in a tiny fiber.' },
    { title: 'Penguins huddle with math-like movement', detail: 'They rotate positions to share warmth.' },
    { title: 'Sharks sense electric fields', detail: 'Special organs detect tiny signals from prey.' },
    { title: 'Butterflies migrate thousands of kilometers', detail: 'Some migrations span generations.' },
    { title: 'The mimic octopus changes identity', detail: 'It can imitate the appearance and movement of other animals.' },
    { title: 'Platypuses detect prey electrically', detail: 'They use electroreception while hunting underwater.' },
  ],
  science: [
    { title: 'Atoms are mostly empty space', detail: 'Matter feels solid because of forces, not because atoms are packed tight.' },
    { title: 'Hot water can sometimes freeze faster', detail: 'The Mpemba effect appears under certain conditions.' },
    { title: 'DNA stores biological instructions', detail: 'A tiny molecule carries huge amounts of information.' },
    { title: 'Quantum particles can be entangled', detail: 'Linked particles can show correlated behavior across distance.' },
    { title: 'GPS needs relativity', detail: 'Satellite clocks must account for time differences.' },
    { title: 'Water has a triple point', detail: 'Under exact conditions it can coexist as solid, liquid, and gas.' },
    { title: 'Magnets come from moving charges', detail: 'Magnetism is tied to electric charge and quantum spin.' },
    { title: 'Lasers are organized light', detail: 'They produce focused beams with aligned wavelengths.' },
    { title: 'Vaccines train immunity', detail: 'They prepare the body to respond to threats.' },
    { title: 'Catalysts speed reactions', detail: 'They help reactions happen without being consumed.' },
    { title: 'Superconductors lose resistance', detail: 'Some materials conduct electricity with zero resistance at low temperatures.' },
    { title: 'Chaos can be deterministic', detail: 'Tiny changes can create huge differences in complex systems.' },
    { title: 'Spectroscopy reads light signatures', detail: 'Scientists identify materials by how they absorb or emit light.' },
    { title: 'Particle accelerators recreate extremes', detail: 'They smash particles to study fundamental physics.' },
    { title: 'CRISPR edits genetic sequences', detail: 'It gives scientists a precise way to modify DNA.' },
    { title: 'Photosynthesis powers ecosystems', detail: 'Plants convert light into chemical energy.' },
    { title: 'Thermodynamics rules energy', detail: 'Heat, work, and entropy shape every machine and organism.' },
    { title: 'Nanotechnology works at tiny scales', detail: 'Materials behave differently when structured near atomic sizes.' },
    { title: 'Radioactivity changes atoms', detail: 'Unstable nuclei release particles or energy.' },
    { title: 'Materials science builds the future', detail: 'New materials can change batteries, medicine, transport, and computing.' },
  ],
  ocean: [
    { title: 'Most of the ocean is still poorly explored', detail: 'The deep sea is hard to reach, map, and study.' },
    { title: 'There are underwater lakes', detail: 'Dense salty brine can form lake-like pools on the seafloor.' },
    { title: 'Some fish make their own light', detail: 'Bioluminescence helps with hunting, hiding, and communication.' },
    { title: 'Hydrothermal vents host strange life', detail: 'Entire ecosystems survive without sunlight.' },
    { title: 'Marine snow feeds the deep sea', detail: 'Falling organic particles carry food into dark depths.' },
    { title: 'Ocean currents move heat globally', detail: 'Currents help regulate climate and weather.' },
    { title: 'Deep trenches are extreme worlds', detail: 'Pressure rises enormously at the deepest points.' },
    { title: 'Whale falls create ecosystems', detail: 'A dead whale can feed deep-sea life for years.' },
    { title: 'Corals can spawn together', detail: 'Mass spawning events release eggs and sperm into the water.' },
    { title: 'Seamounts are underwater mountains', detail: 'They can host rich communities of marine life.' },
    { title: 'Kelp forests grow underwater', detail: 'They provide habitat and absorb carbon.' },
    { title: 'Mangroves are ocean nurseries', detail: 'Their roots shelter young fish and crustaceans.' },
    { title: 'Tides are driven by gravity', detail: 'The Moon and Sun pull on Earth’s oceans.' },
    { title: 'Sound travels far underwater', detail: 'Low-frequency sound can cross great distances.' },
    { title: 'Sea ice affects climate', detail: 'Ice reflects sunlight and shapes polar ecosystems.' },
    { title: 'Dead zones lack oxygen', detail: 'Excess nutrients can trigger blooms that remove oxygen.' },
    { title: 'Salinity creates layers', detail: 'Salt and temperature differences shape ocean structure.' },
    { title: 'The giant squid was once legendary', detail: 'Real deep-sea animals inspired sea monster stories.' },
    { title: 'The ocean stores carbon', detail: 'Physical and biological processes move carbon into water and sediments.' },
    { title: 'Waves can travel across oceans', detail: 'Energy from storms can move far beyond where it began.' },
  ],
  space: [
    { title: 'Black holes slow time nearby', detail: 'Strong gravity changes how time passes for observers.' },
    { title: 'Space has rogue planets', detail: 'Some planets may drift without a star.' },
    { title: 'Vacuum is not completely empty', detail: 'Space contains particles, fields, radiation, and dust.' },
    { title: 'Cosmic rays hit Earth constantly', detail: 'High-energy particles arrive from space.' },
    { title: 'The ISS falls around Earth', detail: 'Orbit is continuous falling while moving forward fast enough to miss Earth.' },
    { title: 'Mars has planet-wide dust storms', detail: 'Fine dust can spread through the thin atmosphere.' },
    { title: 'Moon dust is sharp', detail: 'Lunar regolith is not weathered like Earth sand.' },
    { title: 'Space debris is a growing problem', detail: 'Fast-moving objects can threaten satellites and spacecraft.' },
    { title: 'Solar sails use light pressure', detail: 'Photons can push reflective sails through space.' },
    { title: 'Microgravity changes the body', detail: 'Muscles, bones, and fluids adapt differently in orbit.' },
    { title: 'Space suits are mini spacecraft', detail: 'They manage pressure, oxygen, temperature, and protection.' },
    { title: 'Radiation belts surround Earth', detail: 'Charged particles are trapped by the magnetic field.' },
    { title: 'Orbital mechanics is counterintuitive', detail: 'Speeding up can raise orbit in unexpected ways.' },
    { title: 'Some moons have cryovolcanoes', detail: 'They can erupt water, ice, or other frozen materials.' },
    { title: 'Exoplanet atmospheres can be studied', detail: 'Light passing through atmospheres reveals chemical clues.' },
    { title: 'Asteroids may contain valuable metals', detail: 'Their materials preserve early solar system history.' },
    { title: 'Interstellar probes face huge distances', detail: 'Even nearby stars are unimaginably far away.' },
    { title: 'Moonquakes happen', detail: 'The Moon has seismic activity caused by tides, cooling, and impacts.' },
    { title: 'Terraforming is extremely hard', detail: 'Changing a planet’s environment would require enormous energy and time.' },
    { title: 'The Sun controls space weather', detail: 'Solar activity shapes conditions throughout the solar system.' },
  ],
  earth: [
    { title: 'Earth’s core is extremely hot', detail: 'The inner core reaches temperatures comparable to the Sun’s surface.' },
    { title: 'Continents are still moving', detail: 'Tectonic plates drift slowly over geologic time.' },
    { title: 'Atmospheric rivers carry water', detail: 'Narrow bands of vapor can deliver intense rainfall.' },
    { title: 'Earth has a magnetic shield', detail: 'The magnetic field helps protect against solar particles.' },
    { title: 'Supervolcanoes can reshape climate', detail: 'Huge eruptions can inject particles into the atmosphere.' },
    { title: 'Mountains are still rising', detail: 'Plate collisions can lift rock over millions of years.' },
    { title: 'Earthquakes release stored stress', detail: 'Faults move when pressure overcomes friction.' },
    { title: 'Crystals grow in nature', detail: 'Minerals form ordered structures under the right conditions.' },
    { title: 'Caves record ancient climates', detail: 'Stalagmites and stalactites can preserve environmental clues.' },
    { title: 'Glaciers flow like slow rivers', detail: 'Ice deforms and moves under its own weight.' },
    { title: 'Desert dunes migrate', detail: 'Wind moves sand and changes dune shapes.' },
    { title: 'River deltas build land', detail: 'Sediment carried by rivers can create new landscapes.' },
    { title: 'Monsoons are seasonal systems', detail: 'Large wind shifts bring wet and dry seasons.' },
    { title: 'Island arcs form near subduction zones', detail: 'One plate sinking under another can create chains of volcanic islands.' },
    { title: 'Soil takes time to form', detail: 'Rock, climate, organisms, and time create fertile ground.' },
    { title: 'The ozone layer blocks UV', detail: 'Ozone high in the atmosphere absorbs harmful ultraviolet radiation.' },
    { title: 'Jet streams steer weather', detail: 'Fast winds high in the atmosphere influence storms.' },
    { title: 'Sinkholes can open suddenly', detail: 'Underground cavities can collapse when support fails.' },
    { title: 'Geothermal energy comes from Earth’s heat', detail: 'Heat from inside the planet can be used for power and heating.' },
    { title: 'Fossils are rare accidents', detail: 'Most living things disappear without becoming fossils.' },
  ],
  technology: [
    { title: 'Phones beat early spacecraft computers', detail: 'Modern smartphones have enormous computing power compared with early machines.' },
    { title: 'The first computer bug was literal', detail: 'A moth found in a relay helped popularize debugging.' },
    { title: 'AI learns patterns', detail: 'Machine learning systems detect statistical structure in data.' },
    { title: 'The internet breaks data into packets', detail: 'Information travels in small pieces that are reassembled later.' },
    { title: 'GPS depends on satellites and clocks', detail: 'Precise timing lets receivers calculate location.' },
    { title: 'Semiconductors power modern electronics', detail: 'They control electric current in chips.' },
    { title: 'Encryption protects secrets', detail: 'Math makes information unreadable without the right key.' },
    { title: 'Fiber optics carry light signals', detail: 'Glass fibers transmit data across long distances.' },
    { title: 'Batteries store chemical energy', detail: 'Reactions move electrons through circuits.' },
    { title: 'Robots combine sensors and control', detail: 'They perceive, decide, and act through hardware and software.' },
    { title: '3D printing builds layer by layer', detail: 'Objects can be created from digital designs.' },
    { title: 'Cloud computing is someone else’s data center', detail: 'Remote servers provide storage and processing on demand.' },
    { title: 'Touchscreens detect tiny changes', detail: 'Capacitive screens sense electrical changes from a finger.' },
    { title: 'Computer vision teaches machines to see', detail: 'Algorithms detect shapes, objects, motion, and patterns.' },
    { title: 'Voice assistants turn sound into data', detail: 'Speech recognition converts audio into text and intent.' },
    { title: 'Data centers are hidden infrastructure', detail: 'They power apps, cloud services, AI, and the web.' },
    { title: 'Solar panels turn photons into electricity', detail: 'Light knocks electrons loose in semiconductor material.' },
    { title: 'Wind turbines harvest moving air', detail: 'Blades convert wind energy into rotation and electricity.' },
    { title: 'Blockchain stores shared records', detail: 'Distributed ledgers make tampering difficult through cryptography and consensus.' },
    { title: 'Quantum computers use quantum states', detail: 'They process information in ways different from classical bits.' },
  ],
  psychology: [
    { title: 'Memory is rebuilt', detail: 'The brain reconstructs memories and can change details.' },
    { title: 'Attention can hide the obvious', detail: 'Focused attention can make visible events go unnoticed.' },
    { title: 'Music changes perceived time', detail: 'Tempo and emotion can make time feel faster or slower.' },
    { title: 'The placebo effect can be real', detail: 'Belief and expectation can influence physical responses.' },
    { title: 'Decision fatigue affects choices', detail: 'Mental effort can reduce self-control and patience.' },
    { title: 'Confirmation bias filters evidence', detail: 'People notice information that supports what they already believe.' },
    { title: 'Emotions can spread socially', detail: 'People can unconsciously mirror moods and expressions.' },
    { title: 'Sleep strengthens learning', detail: 'Rest helps consolidate memories and skills.' },
    { title: 'Fear narrows attention', detail: 'Threat response focuses the mind on survival cues.' },
    { title: 'Habits run on loops', detail: 'Cues, routines, and rewards shape repeated behavior.' },
    { title: 'Color can influence perception', detail: 'Context changes how colors and signals are interpreted.' },
    { title: 'Social proof guides behavior', detail: 'People often copy what others appear to be doing.' },
    { title: 'Phantom vibration feels real', detail: 'People sometimes sense phone vibrations that did not happen.' },
    { title: 'The brain creates cognitive maps', detail: 'Mental maps help navigate places and ideas.' },
    { title: 'Pareidolia makes faces appear', detail: 'The brain detects familiar patterns in random shapes.' },
    { title: 'Anchoring changes estimates', detail: 'An initial number can bias later judgments.' },
    { title: 'Flow makes effort feel smooth', detail: 'Deep focus can make time and self-awareness fade.' },
    { title: 'Curiosity boosts learning', detail: 'Questions make information feel more rewarding.' },
    { title: 'Mirror systems support empathy', detail: 'Watching actions and emotions can activate related brain networks.' },
    { title: 'Framing changes decisions', detail: 'The same fact can feel different depending on presentation.' },
  ],
  mysteries: [
    { title: 'The deep ocean hides unknown life', detail: 'New species are still discovered in remote waters.' },
    { title: 'Ancient engineering still raises questions', detail: 'Some building methods remain debated by researchers.' },
    { title: 'Ball lightning is hard to study', detail: 'Reports exist, but the phenomenon is rare and difficult to capture.' },
    { title: 'The Voynich Manuscript remains puzzling', detail: 'Its strange script and illustrations are still debated.' },
    { title: 'Fast radio bursts are cosmic signals', detail: 'Powerful radio flashes arrive from deep space.' },
    { title: 'Dark energy is still mysterious', detail: 'It is linked to the accelerating expansion of the universe.' },
    { title: 'Lost cities keep being found', detail: 'Remote sensing reveals hidden settlements under vegetation and soil.' },
    { title: 'Ancient geoglyphs are massive', detail: 'Huge ground drawings are best seen from above.' },
    { title: 'Strange natural sounds travel far', detail: 'Earth, ice, ocean, and atmosphere can create eerie signals.' },
    { title: 'Hidden chambers may remain undiscovered', detail: 'Ancient structures can still contain sealed spaces.' },
    { title: 'Megalithic sites spark debate', detail: 'The movement and placement of huge stones can be difficult to explain.' },
    { title: 'Missing expeditions become legends', detail: 'Harsh environments and poor records leave unanswered questions.' },
    { title: 'Unidentified fossils challenge categories', detail: 'Fragmentary remains can be hard to interpret.' },
    { title: 'Cryptic manuscripts resist decoding', detail: 'Unknown languages and symbols can stay unsolved for centuries.' },
    { title: 'Strange signals can have simple causes', detail: 'Many mysteries become clearer after better instruments and data.' },
    { title: 'Natural anomalies look supernatural', detail: 'Rare physics, weather, or geology can create unbelievable sights.' },
    { title: 'The Bermuda Triangle is mostly myth', detail: 'Stories often mix real accidents with exaggeration.' },
    { title: 'Archaeological puzzles evolve', detail: 'New dating and scanning methods change old explanations.' },
    { title: 'Historical riddles depend on evidence', detail: 'A single document or artifact can shift interpretation.' },
    { title: 'Some mysteries remain open', detail: 'Not every question has enough evidence for a final answer.' },
  ],
  'ancient-world': [
    { title: 'Ancient cities had infrastructure', detail: 'Drainage, streets, walls, and water systems existed thousands of years ago.' },
    { title: 'The Antikythera mechanism was advanced', detail: 'Its gears modeled astronomical cycles.' },
    { title: 'Ancient trade connected continents', detail: 'Goods and ideas moved across huge distances.' },
    { title: 'Egyptian medicine was complex', detail: 'Texts describe diagnosis, treatments, and surgical knowledge.' },
    { title: 'Mesopotamia developed writing', detail: 'Cuneiform helped record trade, law, and stories.' },
    { title: 'Indus cities had planned layouts', detail: 'Some settlements show organized streets and drainage.' },
    { title: 'Roman roads lasted centuries', detail: 'Engineering helped connect the empire.' },
    { title: 'Greek astronomy was mathematical', detail: 'Ancient thinkers modeled planetary motion and eclipses.' },
    { title: 'Mayan calendars tracked cycles', detail: 'Astronomy and ritual timekeeping were deeply connected.' },
    { title: 'Ancient metallurgy changed warfare', detail: 'Bronze and iron reshaped tools, weapons, and economies.' },
    { title: 'Persian couriers moved messages fast', detail: 'Relay systems improved imperial communication.' },
    { title: 'China built an early seismograph', detail: 'Ancient inventors designed instruments to detect earthquakes.' },
    { title: 'Nubia built pyramids too', detail: 'The Nile region contained multiple pyramid-building cultures.' },
    { title: 'Phoenicians were skilled sailors', detail: 'They spread trade, writing, and navigation across the Mediterranean.' },
    { title: 'Aqueducts moved water by gravity', detail: 'Precise engineering supplied cities with water.' },
    { title: 'The Terracotta Army guarded a tomb', detail: 'Thousands of figures were made for an emperor’s afterlife.' },
    { title: 'Sumerian cities shaped civilization', detail: 'Urban life, writing, and administration developed early there.' },
    { title: 'Inca roads crossed mountains', detail: 'A vast road network connected difficult terrain.' },
    { title: 'Ancient shipbuilding was sophisticated', detail: 'Maritime trade required strong design and navigation.' },
    { title: 'Old libraries preserved power', detail: 'Control of knowledge was a form of cultural influence.' },
  ],
  'weird-facts': [
    { title: 'Bananas are berries', detail: 'Botanical definitions differ from everyday food categories.' },
    { title: 'Some turtles breathe through the rear', detail: 'Certain species absorb oxygen through specialized tissues.' },
    { title: 'Clouds can weigh hundreds of tons', detail: 'Tiny droplets add up across enormous volumes.' },
    { title: 'Honey can last very long', detail: 'Low water content and acidity help preserve it.' },
    { title: 'Some lakes are naturally pink', detail: 'Microbes and minerals can create unusual colors.' },
    { title: 'Singing sand makes sound', detail: 'Moving grains can produce humming or booming noises.' },
    { title: 'Blue lava is actually blue flame', detail: 'Burning sulfur can create a glowing blue effect.' },
    { title: 'Metal can melt in your hand', detail: 'Gallium melts at a low temperature.' },
    { title: 'Square waves can be dangerous', detail: 'Intersecting wave systems create a checkerboard sea pattern.' },
    { title: 'Ice spikes grow upward', detail: 'Freezing water can push ice into strange shapes.' },
    { title: 'Some bacteria are magnetic', detail: 'Magnetotactic bacteria align with magnetic fields.' },
    { title: 'Blood Falls looks red', detail: 'Iron-rich water can create a blood-like color on ice.' },
    { title: 'Glowing waves are real', detail: 'Bioluminescent plankton can light up moving water.' },
    { title: 'Some trees can explode seed pods', detail: 'Certain plants launch seeds with sudden force.' },
    { title: 'The immortal jellyfish can reverse age stage', detail: 'It can return to an earlier life stage under some conditions.' },
    { title: 'Raining animals stories exist', detail: 'Waterspouts may lift small animals and drop them elsewhere.' },
    { title: 'Green flashes happen at sunset', detail: 'Atmospheric refraction can create a brief green light.' },
    { title: 'Left-handed snails can confuse predators', detail: 'Shell direction can affect predator handling.' },
    { title: 'Walking palms are debated', detail: 'Some trees appear to shift position gradually through root growth.' },
    { title: 'Some facts sound fake but are taxonomy', detail: 'Scientific classification often clashes with everyday language.' },
  ],
}

function expandTopics(category: string, seeds: FactSeed[]): MindBlowingFact[] {
  return topicAngles.flatMap(angle =>
    seeds.map(seed => ({
      category,
      title: `${seed.title} — ${angle.prefix}`,
      text: `${seed.detail} ${angle.focus}`,
    }))
  ).slice(0, 100)
}

export const factsByCategory: Record<string, MindBlowingFact[]> = Object.fromEntries(
  factCategories.map(category => [
    category.id,
    expandTopics(category.title, topicSeeds[category.id]),
  ])
)

export function getFactsForCategory(id: string) {
  return factsByCategory[id] || factsByCategory['weird-facts']
}

export function getFactCategory(id: string) {
  return factCategories.find(category => category.id === id) || factCategories[0]
}
