import { NextResponse } from 'next/server'

export const revalidate = 3600

type MediaType = 'movie' | 'series' | 'cartoon'
type Item = { id: string; type: MediaType; title: string; originalTitle: string; year: string; image: string; summary: string; genres: string[]; rating: number | null; url: string; trailerUrl: string; source: string }
type Seed = { type: MediaType; title: string; year: number; genres: string[]; trend?: boolean; anticipated?: boolean }

const H = 'https://'
const TMDB_KEY = process.env.TMDB_API_KEY || ''
const TMDB_TOKEN = process.env.TMDB_READ_ACCESS_TOKEN || ''
const OMDB_KEY = process.env.OMDB_API_KEY || ''
const IMG = H + 'image.tmdb.org/t/p/w500'
const MOVIE_GENRES: Record<string, number> = { Action: 28, Adventure: 12, Animation: 16, Comedy: 35, Crime: 80, Drama: 18, Family: 10751, Fantasy: 14, Romance: 10749, Thriller: 53, 'Science-Fiction': 878 }
const TV_GENRES: Record<string, number> = { Action: 10759, Adventure: 10759, Animation: 16, Comedy: 35, Crime: 80, Drama: 18, Family: 10751, Fantasy: 10765, Thriller: 9648, 'Science-Fiction': 10765 }
const SEEDS: Seed[] = [
  { type: 'movie', title: 'The Godfather', year: 1972, genres: ['Drama', 'Crime'], trend: true }, { type: 'movie', title: 'The Matrix', year: 1999, genres: ['Action', 'Science-Fiction'] }, { type: 'movie', title: 'The Dark Knight', year: 2008, genres: ['Action', 'Crime', 'Drama'], trend: true }, { type: 'movie', title: 'Inception', year: 2010, genres: ['Science-Fiction', 'Action', 'Thriller'], trend: true }, { type: 'movie', title: 'Interstellar', year: 2014, genres: ['Science-Fiction', 'Drama'], trend: true }, { type: 'movie', title: 'Dune', year: 2021, genres: ['Science-Fiction', 'Adventure'], trend: true }, { type: 'movie', title: 'Oppenheimer', year: 2023, genres: ['Drama', 'Thriller'], trend: true }, { type: 'movie', title: 'Dune: Part Two', year: 2024, genres: ['Science-Fiction', 'Adventure'], trend: true }, { type: 'movie', title: 'Superman', year: 2025, genres: ['Action', 'Adventure'], anticipated: true },
  { type: 'series', title: 'Breaking Bad', year: 2008, genres: ['Drama', 'Crime'], trend: true }, { type: 'series', title: 'Game of Thrones', year: 2011, genres: ['Fantasy', 'Drama'], trend: true }, { type: 'series', title: 'Stranger Things', year: 2016, genres: ['Science-Fiction', 'Drama'], trend: true }, { type: 'series', title: 'Squid Game', year: 2021, genres: ['Drama', 'Thriller'], trend: true }, { type: 'series', title: 'The Last of Us', year: 2023, genres: ['Drama', 'Action'], trend: true }, { type: 'series', title: 'Fallout', year: 2024, genres: ['Science-Fiction', 'Action'], trend: true },
  { type: 'cartoon', title: 'The Lion King', year: 1994, genres: ['Animation', 'Family'], trend: true }, { type: 'cartoon', title: 'Toy Story', year: 1995, genres: ['Animation', 'Family'] }, { type: 'cartoon', title: 'Shrek', year: 2001, genres: ['Animation', 'Comedy'] }, { type: 'cartoon', title: 'Finding Nemo', year: 2003, genres: ['Animation', 'Family'] }, { type: 'cartoon', title: 'Frozen', year: 2013, genres: ['Animation', 'Family'], trend: true }, { type: 'cartoon', title: 'Inside Out', year: 2015, genres: ['Animation', 'Family'], trend: true }, { type: 'cartoon', title: 'Inside Out 2', year: 2024, genres: ['Animation', 'Family'], trend: true }, { type: 'cartoon', title: 'Toy Story 5', year: 2026, genres: ['Animation', 'Family'], anticipated: true },
]
function norm(v: string) { return v.toLowerCase().replace(/[^a-z0-9]+/g, '') }
function strip(v?: string) { return (v || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim() }
function lang(l: string) { return ({ az: 'az-AZ', ru: 'ru-RU', de: 'de-DE', tr: 'tr-TR', en: 'en-US' } as Record<string, string>)[l] || 'en-US' }
function fallback(seed: Seed) { const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="900"><rect width="600" height="900" fill="#111827"/><rect width="600" height="900" fill="#7c3aed" opacity=".35"/><text x="40" y="100" fill="white" font-family="Arial" font-size="28" font-weight="700">${seed.type.toUpperCase()} · ${seed.year}</text><text x="40" y="430" fill="white" font-family="Arial" font-size="44" font-weight="800">${seed.title.replace(/&/g, '&amp;')}</text></svg>`; return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}` }
function pass(i: Item, type: MediaType, genre: string, from: number | null, to: number | null, q: string) { return i.type === type && (!genre || i.genres.some(g => g.toLowerCase() === genre.toLowerCase()) || (type === 'cartoon' && genre === 'Animation')) && (!from || !i.year || Number(i.year) >= from) && (!to || !i.year || Number(i.year) <= to) && (!q || i.title.toLowerCase().includes(q.toLowerCase()) || i.originalTitle.toLowerCase().includes(q.toLowerCase())) }
async function tmdbFetch(path: string, params: Record<string, string | number | undefined>) { if (!TMDB_KEY && !TMDB_TOKEN) return null; const u = new URL(H + 'api.themoviedb.org/3' + path); Object.entries(params).forEach(([k, v]) => { if (v !== undefined && v !== '') u.searchParams.set(k, String(v)) }); if (TMDB_KEY) u.searchParams.set('api_key', TMDB_KEY); const headers: HeadersInit = {}; if (TMDB_TOKEN) headers.Authorization = `Bearer ${TMDB_TOKEN}`; try { const r = await fetch(u.toString(), { headers, next: { revalidate: 3600 } }); return r.ok ? await r.json() : null } catch { return null } }
function tmdbItem(r: any, type: MediaType, map: Record<number, string>): Item { const title = r.title || r.name || r.original_title || r.original_name || 'Untitled'; const originalTitle = r.original_title || r.original_name || title; const date = r.release_date || r.first_air_date || ''; const year = date ? String(date).slice(0, 4) : ''; const genres = Array.isArray(r.genre_ids) ? r.genre_ids.map((id: number) => map[id]).filter(Boolean) : []; const media = type === 'series' ? 'tv' : 'movie'; return { id: `tmdb-${media}-${r.id}`, type, title, originalTitle, year, image: r.poster_path ? IMG + r.poster_path : fallback({ type, title, year: Number(year) || 0, genres }), summary: r.overview || `${title} · ${year}`, genres, rating: typeof r.vote_average === 'number' ? Number(r.vote_average.toFixed(1)) : null, url: H + `www.themoviedb.org/${media}/${r.id}`, trailerUrl: H + `www.youtube.com/results?search_query=${encodeURIComponent(originalTitle + ' official trailer')}`, source: 'TMDb' } }
async function getTmdb(type: MediaType, mode: string, l: string, q: string, genre: string, from: number | null, to: number | null): Promise<Item[]> { const media = type === 'series' ? 'tv' : 'movie'; const gs = type === 'series' ? TV_GENRES : MOVIE_GENRES; const map: Record<number, string> = Object.fromEntries(Object.entries(gs).map(([n, id]) => [id, n])); const gid = gs[genre]; let endpoint = `/discover/${media}`; const params: Record<string, string | number | undefined> = { language: lang(l), sort_by: 'popularity.desc', include_adult: 'false', page: 1 }; if (q) { endpoint = `/search/${media}`; params.query = q } else if (mode === 'trending') endpoint = `/trending/${media}/week`; else if (mode === 'anticipated') endpoint = type === 'series' ? '/discover/tv' : '/movie/upcoming'; if (!q && endpoint.includes('/discover/')) { if (type === 'cartoon') params.with_genres = gid ? `${MOVIE_GENRES.Animation},${gid}` : `${MOVIE_GENRES.Animation}`; else if (gid) params.with_genres = gid; if (from) params[type === 'series' ? 'first_air_date.gte' : 'primary_release_date.gte'] = `${from}-01-01`; if (to) params[type === 'series' ? 'first_air_date.lte' : 'primary_release_date.lte'] = `${to}-12-31` } const d = await tmdbFetch(endpoint, params); return (Array.isArray(d?.results) ? d.results : []).map((r: any) => tmdbItem(r, type, map)).filter(i => pass(i, type, genre, from, to, q)) }
async function getTvMaze(q: string): Promise<Item[]> { try { const u = q ? H + 'api.tvmaze.com/search/shows?q=' + encodeURIComponent(q) : H + 'api.tvmaze.com/shows?page=1'; const d = await (await fetch(u, { next: { revalidate: 3600 } })).json(); const rows = q ? (Array.isArray(d) ? d.map((x: any) => x.show) : []) : (Array.isArray(d) ? d : []); return rows.slice(0, 50).map((s: any): Item => ({ id: `tvmaze-${s.id}`, type: 'series', title: s.name, originalTitle: s.name, year: s.premiered ? String(s.premiered).slice(0, 4) : '', image: s.image?.original || s.image?.medium || fallback({ type: 'series', title: s.name, year: 0, genres: s.genres || [] }), summary: strip(s.summary), genres: s.genres || [], rating: s.rating?.average || null, url: s.officialSite || s.url, trailerUrl: H + 'www.youtube.com/results?search_query=' + encodeURIComponent(s.name + ' official trailer'), source: 'TVMaze' })) } catch { return [] } }
async function getJikan(q: string, mode: string): Promise<Item[]> { try { const u = q ? H + 'api.jikan.moe/v4/anime?q=' + encodeURIComponent(q) + '&limit=24' : H + 'api.jikan.moe/v4/top/anime?limit=24' + (mode === 'anticipated' ? '&filter=upcoming' : ''); const d = await (await fetch(u, { next: { revalidate: 3600 } })).json(); return (Array.isArray(d?.data) ? d.data : []).map((a: any): Item => ({ id: `jikan-${a.mal_id}`, type: 'cartoon', title: a.title_english || a.title, originalTitle: a.title, year: a.year ? String(a.year) : (a.aired?.from ? String(a.aired.from).slice(0, 4) : ''), image: a.images?.jpg?.large_image_url || a.images?.webp?.large_image_url || fallback({ type: 'cartoon', title: a.title, year: 0, genres: ['Animation'] }), summary: strip(a.synopsis), genres: ['Animation', ...(a.genres || []).map((g: any) => g.name).slice(0, 2)], rating: a.score || null, url: a.url, trailerUrl: a.trailer?.url || H + 'www.youtube.com/results?search_query=' + encodeURIComponent(a.title + ' trailer'), source: 'Jikan' })) } catch { return [] } }
async function wiki(seed: Seed) { for (const title of [seed.title, `${seed.title} (film)`, `${seed.title} (TV series)`]) try { const r = await fetch(H + 'en.wikipedia.org/api/rest_v1/page/summary/' + encodeURIComponent(title), { next: { revalidate: 3600 } }); if (!r.ok) continue; const d = await r.json(); return { image: d?.thumbnail?.source || d?.originalimage?.source, summary: strip(d?.extract), url: d?.content_urls?.desktop?.page } } catch {} return null }
async function seedItems(type: MediaType, mode: string, q: string, genre: string, from: number | null, to: number | null): Promise<Item[]> { let seeds = SEEDS.filter(s => s.type === type); if (mode === 'trending') seeds = seeds.filter(s => s.trend); if (mode === 'anticipated') seeds = seeds.filter(s => s.anticipated || s.year >= new Date().getFullYear()); seeds = seeds.filter(s => (!q || s.title.toLowerCase().includes(q.toLowerCase())) && (!genre || s.genres.some(g => g.toLowerCase() === genre.toLowerCase())) && (!from || s.year >= from) && (!to || s.year <= to)); return Promise.all(seeds.map(async s => { const w = await wiki(s); return { id: `seed-${s.type}-${norm(s.title)}`, type: s.type, title: s.title, originalTitle: s.title, year: String(s.year), image: w?.image || fallback(s), summary: w?.summary || `${s.title} · ${s.year}`, genres: s.genres, rating: null, url: w?.url || H + 'www.google.com/search?q=' + encodeURIComponent(s.title), trailerUrl: H + 'www.youtube.com/results?search_query=' + encodeURIComponent(s.title + ' trailer'), source: w?.image ? 'Wikipedia' : 'Local' } as Item })) }
async function enrich(item: Item): Promise<Item> { if (!OMDB_KEY) return item; try { const u = new URL(H + 'www.omdbapi.com/'); u.searchParams.set('apikey', OMDB_KEY); u.searchParams.set('t', item.originalTitle || item.title); if (item.year) u.searchParams.set('y', item.year); const d = await (await fetch(u.toString(), { next: { revalidate: 3600 } })).json(); if (d?.Response === 'False') return item; return { ...item, image: item.image.startsWith('data:') && d.Poster && d.Poster !== 'N/A' ? d.Poster : item.image, summary: item.summary || d.Plot || item.summary, rating: item.rating || (d.imdbRating && d.imdbRating !== 'N/A' ? Number(d.imdbRating) : null), url: d.imdbID ? H + `www.imdb.com/title/${d.imdbID}/` : item.url, source: `${item.source}+OMDb` } } catch { return item } }
function unique(items: Item[]) { const seen = new Set<string>(); return items.filter(i => { const k = `${i.type}-${norm(i.originalTitle || i.title)}-${i.year}`; if (seen.has(k)) return false; seen.add(k); return true }) }
async function trTexts(texts: string[], l: string) { if (!l || l === 'en' || !texts.length) return texts; try { const r = await fetch(H + 'translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=' + l + '&dt=t&q=' + encodeURIComponent(texts.join('\n---\n'))); const d = await r.json(); return (d?.[0]?.map((x: any) => x?.[0]).join('') || texts.join('\n---\n')).split('\n---\n') } catch { return texts } }

export async function GET(req: Request) {
  const sp = new URL(req.url).searchParams
  const type = (sp.get('type') || 'movie') as MediaType | 'all'
  const genre = sp.get('genre') || '', l = sp.get('lang') || 'en', q = sp.get('q') || '', mode = sp.get('mode') || 'default'
  const from = sp.get('yearFrom') ? Number(sp.get('yearFrom')) : null, to = sp.get('yearTo') ? Number(sp.get('yearTo')) : null
  const types: MediaType[] = type === 'all' ? ['movie', 'series', 'cartoon'] : [type as MediaType]
  let items: Item[] = []
  for (const t of types) { const parts = await Promise.all([getTmdb(t, mode, l, q, genre, from, to), t === 'series' ? getTvMaze(q) : Promise.resolve([]), t === 'cartoon' ? getJikan(q, mode) : Promise.resolve([]), seedItems(t, mode, q, genre, from, to)]); items.push(...parts.flat().filter(i => pass(i, t, genre, from, to, q))) }
  items = unique(items).sort((a, b) => Number(!a.image.startsWith('data:')) - Number(!b.image.startsWith('data:')) || Number(b.rating || 0) - Number(a.rating || 0) || Number(b.year || 0) - Number(a.year || 0)).slice(0, 80)
  if (OMDB_KEY) items = await Promise.all(items.slice(0, 50).map(enrich))
  if (l !== 'en') { const titles = await trTexts(items.map(i => i.title), l); const sums = await trTexts(items.map(i => i.summary || ''), l); items = items.map((it, i) => ({ ...it, title: titles[i] || it.title, summary: sums[i] || it.summary })) }
  return NextResponse.json(items)
}
